# Optimization of sartorious transfer paramters of viscous liquids guided by Baysesian Optimization

## Summary

This notebook objective is to generate new suggestions of aspiration and dispense rates that will minimize the tansfer error while minimizing the time of transfer of a viscous liquid. The code in this notebook will aim to optimize the liquid transfer parameters  to minimize the mean error from three volumes (default 300, 500, 1000) and the time of transfer to dispense 1000 uL.
The code is strucutred as follows:
1.  Fisrt section is for importing the relevant packages to perform BO, inclduing Pytorch and BOtorch
2.  Second section includes the definition of the BO_LiqTransfer class that includes the method optimized_suggestions() that generates BO optimized aspiration and dispense rate values for a particular data set.
3. Third section includes the code to initialize the automated platform.
4. Fourth section includes the code to run experiments using M1 robotic arm attached with electronic pipette, automated mass balance and BO optimization of a viscous liquid. The steps for the optimziation are:

    i. Initilize a BO_LiTransfer objecet and load initilization data using data_from_csv() method

    ii. Run optimized_suggestions() method

    iii. Run liquid transfer gravimetric experiment using the best suggestion for aspiration and dispense rates

    iv. Update latest %error obtained from the transfer using suggested aspiration and dispense rates.
    
    v. Iterate through steps ii-iV

## 1. Imports

In [1]:
# basic dependencies

import numpy as np
from numpy import loadtxt
from numpy import savetxt

import pandas as pd
import math
import time
from datetime import date

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

###########

# torch dependencies
import torch

tkwargs = {"dtype": torch.double, # set as double to minimize zero error for cholesky decomposition error
           "device": torch.device("cuda:0" if torch.cuda.is_available() else "cpu")} # set tensors to GPU, if multiple GPUs please set cuda:x properly

torch.set_printoptions(precision=3)

###########

# botorch dependencies
import botorch

# data related
from botorch.utils.sampling import draw_sobol_samples
from botorch.utils.transforms import unnormalize, normalize

# surrogate model specific
from botorch.models.gp_regression import SingleTaskGP
from botorch.models.model_list_gp_regression import ModelListGP
from botorch.models.transforms.outcome import Standardize
from gpytorch.mlls.sum_marginal_log_likelihood import SumMarginalLogLikelihood
from botorch import fit_gpytorch_model

# qNEHVI specific
from botorch.acquisition.multi_objective.objective import IdentityMCMultiOutputObjective
from botorch.acquisition.objective import IdentityMCObjective
from botorch.acquisition import qNoisyExpectedImprovement

# utilities
from botorch.optim.optimize import optimize_acqf
from botorch.sampling import SobolQMCNormalSampler
from botorch.utils.multi_objective.pareto import is_non_dominated
from botorch.utils.multi_objective.hypervolume import Hypervolume
from typing import Optional
from torch import Tensor
from botorch.exceptions import BadInitialCandidatesWarning

from gpytorch.constraints import GreaterThan
from torch.optim import SGD
from gpytorch.mlls import ExactMarginalLogLikelihood

import warnings

warnings.filterwarnings('ignore', category=BadInitialCandidatesWarning)
warnings.filterwarnings('ignore', category=RuntimeWarning)


# plotting dependencies
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline

SMALL_SIZE = 14
MEDIUM_SIZE = 18
BIGGER_SIZE = 20

plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title


C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## 2. BO_LiqTransfer class

In [2]:
class BO_LiqTransfer:

    def __init__(self, liquid_name):
        self.liquid_name = liquid_name
        self._data = None
        self.features = ['aspiration_rate','dispense_rate']
        self.objectives = ['%error']
        self.bmax = 1.25
        self.bmin = 0.1
        self._latest_suggestion = None
        self._latest_volume = None
        self._latest_acq_value = None
        self.mean_volumes = [100,500,1000]
    
   
    def set_data(self,df):
        df['time_asp_1000'] = 1000/df['aspiration_rate'] + 1000/df['dispense_rate'] + df['delay_aspirate'] + df['delay_dispense']
        if 'acq_value' not in df.columns:
            df['acq_value'] = None

        if df.loc[:,self.features].duplicated().sum()==0:
            df_mean = df
        else:
            df_duplicates = df.where(df.duplicated(self.features,keep=False)==True).dropna(how='all')
            df_incomplete = df.where(df.duplicated(self.features,keep=False)==False).dropna(how='all')
            df_mean = pd.DataFrame(columns= df.columns)
            for index,values in df_duplicates.drop_duplicates(self.features).iterrows():
                if len(df_duplicates.loc[index:index+2]) == len(self.mean_volumes):
                    mean_error =df_duplicates.loc[index:index+2,'%error'].abs().mean()
                    df_duplicates.loc[index,'%error'] = -mean_error
                    df_duplicates.loc[index, 'volume'] ='mean'+str(self.mean_volumes)
                    df_mean = pd.concat([df_mean,df.loc[index:index+2],df_duplicates.loc[[index]]])
                else:
                    df_incomplete = pd.concat([df_incomplete,df_duplicates.loc[index:index+2]]).drop_duplicates()
            df_mean = pd.concat([df_mean,df_incomplete])
            df_mean = df_mean.reset_index(drop=True)    
        self._data = df_mean
      

    def data_from_csv(self,file_name):
        data = pd.read_csv(file_name)
        self.set_data(data)



    def update_data(self,df):
        self._latest_volume = df['volume'].iloc[-1]
        updated_data = pd.concat([self._data,df],ignore_index=True)
        self.set_data(updated_data)
        return self._data
                                

    def xy_split(self):
        df_train = self._data.where(self._data['volume']=='mean'+str(self.mean_volumes)).dropna(how='all')
        x_train = df_train[self.features]
        y_train = df_train[self.objectives]
        return x_train,y_train

    def set_bounds(self, x_train):
        return torch.vstack([x_train[0]*self.bmin, x_train[0]*self.bmax])



    def fit_surrogate(self):
        x_train, y_train = self.xy_split()
        x_train = torch.tensor(x_train.to_numpy(dtype=float), **tkwargs)
        y_train = torch.tensor(y_train.to_numpy(dtype=float), **tkwargs)
        y_train = -torch.absolute(y_train)
        

        problem_bounds = self.set_bounds(x_train)
       
        train_x_gp = normalize(x_train, problem_bounds)
        model1 = SingleTaskGP(train_x_gp, y_train, outcome_transform=Standardize(m=1))
        mll1 = ExactMarginalLogLikelihood(model1.likelihood, model1)

        fit_gpytorch_model(mll1)
    
        return model1, train_x_gp, y_train, problem_bounds
    
        
    def optimized_suggestions(self, random_state= 42):
        if random_state != None:
            torch.manual_seed(random_state) 
        standard_bounds = torch.zeros(2, len(self.features), **tkwargs)
        standard_bounds[1] = 1
        model1, train_x_gp, y_train, problem_bounds = self.fit_surrogate()
        acq_func1 = qNoisyExpectedImprovement(
        model=model1,
        X_baseline=train_x_gp, # feed total list of train_x for this current iteration
        sampler=SobolQMCNormalSampler(sample_shape=512),
        prune_baseline=True, cache_pending=True)  # options for improving qNEHVI, keep these on  

        sobol1 = draw_sobol_samples(bounds=standard_bounds,n=512, q=1).squeeze(1)
        sobol2 = draw_sobol_samples(bounds=standard_bounds,n=512, q=1).squeeze(1)
        sobol_all = torch.vstack([sobol1, sobol2])
            
        acq_value_list = []
        for i in range(0, sobol_all.shape[0]):
            with torch.no_grad():
                acq_value = acq_func1(sobol_all[i].unsqueeze(dim=0))
                acq_value_list.append(acq_value.item())
                
        # filter the best 12 QMC candidates first
        sorted_x = sobol_all.cpu().numpy()[np.argsort((acq_value_list))]
        qnei_x = torch.tensor(sorted_x[-12:], **tkwargs)  
        # unormalize our training inputs back to original problem bounds
        new_x =  unnormalize(qnei_x, bounds=problem_bounds)
        new_x = pd.DataFrame(new_x.numpy(),columns=['aspiration_rate','dispense_rate'])
        new_x['acq_value'] = sorted(acq_value_list, reverse=True)[:12]
        self._latest_suggestion = new_x[['aspiration_rate','dispense_rate']].iloc[0]
        self._latest_acq_value = new_x['acq_value'].iloc[0]
        return new_x





        
    
    


## 3. Initialization of automated plarform

In [3]:
#Import relevant python packages
import pandas as pd
import time
from matplotlib import pyplot as plt
from pathlib import Path
import sys
REPOS = 'GitHub'
ROOT = str(Path().absolute()).split(REPOS)[0]
sys.path.append(f'{ROOT}{REPOS}')

from polylectric.configs.SynthesisB1 import SETUP, LAYOUT_FILE

from controllably import load_deck      # optional
load_deck(SETUP.setup, LAYOUT_FILE)     # optional

platform = SETUP
platform.mover.verbose = False


Import: OK <controllably.misc.decorators>
Import: OK <controllably.misc.helper>
Import: OK <controllably.misc.factory>
Import: OK <controllably.misc.layout>
Import: OK <controllably.misc.logger>
Import: OK <controllably.misc.misc_utils>


Import: OK <controllably.Compound.compound_utils>
Import: OK <controllably.Compound.LiquidMover.liquidmover_utils>


Import: OK <controllably.Move.move_utils>
Import: OK <controllably.Move.Jointed.jointed_utils>
Import: OK <controllably.Move.Jointed.Dobot.dobot_utils>
Import: OK <controllably.Move.Jointed.Dobot.m1pro_utils>
Import: OK <controllably.Move.Jointed.Dobot.mg400_utils>
ClearError()
receive: ClearError()
EnableRobot()
receive: EnableRobot()
User(0)
receive: User(0)
Tool(0)
receive: Tool(0)
SetArmOrientation(1,1,1,1)
receive: SetArmOrientation(1,1,1,1)
Infeasible coordinates! (0.0, 0.0, 200.0)
Infeasible coordinates! (300.0, 1.1368683772161603e-13, 0.0)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 3.000s (1.000x

In [4]:
#Initialization of variables for platfomr objects
pipette= platform.setup
deck = platform.setup.deck
balance = platform.balance
balance_deck = deck.slots['1']
source = deck.slots['2']
tip_rack = deck.slots['3']
bin = deck.slots['4']
pipette.mover.setSpeed(50)
print(balance_deck)
print(source)
print(tip_rack)
print(bin)


SpeedFactor(50)
receive: SpeedFactor(50)
Mass_balance_plastic_jar 1 Well Plate 15000 uL at Slot 1
Polyelectric 6 Well Plate 15000 µL at Slot 2
Eppendorf Motion 96 Tip Rack 1000 µL at Slot 3
Polyetric_bin at Slot 4


In [5]:
balance.toggleRecord(False)

In [6]:
#Check if balance is connected
balance.zero()
balance.toggleRecord(True)
time.sleep(5)
print(balance.buffer_df.iloc[-1])
balance.toggleRecord(False)

Listening...
Zeroing... (5s)
Stop listening...
Zeroing complete.
Listening...
Time        2023-07-05 16:26:14.930583
Value                           214370
Factor                        6.862879
Baseline                 214436.313158
Mass                         -9.662585
Name: 24, dtype: object
Stop listening...


In [16]:
pipette.mover.home()

MovJ(206.843094,-146.682146,200.000000,10.000000,0.000000,0.000000)
Move time: 1.265s (1.000x)
[206.843 -146.682 200.000], [10  0  0]
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 1.467s (1.000x)
[300.000 0.000 200.000], [10  0  0]
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (1.000x)
[300.000 0.000 200.000], [10  0  0]
Homed


True

In [11]:
pipette.liquid.eject()

'ok'

In [7]:
pipette.attachTip()

Tip capacitance: 249
A1
Tip capacitance: 248
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (0.200x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
MovJ(198.894071,-3.942538,200.000000,10.000000,0.000000,0.000000)
Move time: 2.022s (0.500x)
[198.894 -3.943 200.000], [10  0  0]
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(198.894071,-3.942538,65.400000,10.000000,0.000000,0.000000)
Move time: 6.730s (0.200x)
[198.894 -3.943 65.400], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
SpeedFactor(1)
receive: SpeedFactor(1)
MovJ(198.894071,-3.942538,45.400000,10.000000,0.000000,0.000000)
Move time: 20.000s (0.010x)
[198.894 -3.943 45.400], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(198.894071,-3.942538,162.300000,10.000000,0.000000,0.000000)
Move time: 5.845s (0.200x)
[198.894 -3.943 162.300], [10  0  0]
SpeedFactor(50)
receive: 

array([325.100, 80.650, 105.900])

In [28]:
#Stablish initial height of liquid on the source vial
pipette_name = 'rLine1000'
initial_liquid_level = 10.5

## 4. Guided BO optimization
i.   Create BO_LiqTransfer object and load data set.

Please set liquid name and volume to transfer according to the experiment.

In [ ]:
# Change according to experiment
std = '1275'
liquid_name = 'Viscosity_std_' + std 
density = 0.8736
# Do not change
liq = BO_LiqTransfer(liquid_name)
folder = (r"C:\Users\admin\Documents\GitHub\viscosity_liquid_transfer_Pablo\Sartorious_experiments\Initialisation_Data\\")
liq.data_from_csv(folder+'Initialisation_'+std+'.csv')
liq._data

In [18]:
# Change according to experiment
std = '817'
liquid_name = 'Viscosity_std_' + std 
density = 0.8466
# Do not change
liq = BO_LiqTransfer(liquid_name)
import os
REPO = 'viscosity_liquid_transfer_Pablo'
folder = os.getcwd().split(REPO)[0]+REPO+r'\Sartorious_experiments\Experimental_Data\\Batch_optimization_data\BOTorch\SOBO\\' #folder that data is saved to
liq.data_from_csv(folder+liquid_name+'_SOBO_BOTorch_exp3_v1.csv')
liq._data

liquid    pipette                volume  aspiration_rate  \
0   Viscosity_std_817  rLine1000                1000.0        54.163119   
1   Viscosity_std_817  rLine1000                 500.0        54.163119   
2   Viscosity_std_817  rLine1000                 300.0        54.163119   
3   Viscosity_std_817  rLine1000  mean[100, 500, 1000]        54.163119   
4   Viscosity_std_817  rLine1000                 300.0        67.703899   
5   Viscosity_std_817  rLine1000                 500.0        67.703899   
6   Viscosity_std_817  rLine1000                1000.0        67.703899   
7   Viscosity_std_817  rLine1000  mean[100, 500, 1000]        67.703899   
8   Viscosity_std_817  rLine1000                 300.0        67.703899   
9   Viscosity_std_817  rLine1000                 500.0        67.703899   
10  Viscosity_std_817  rLine1000                1000.0        67.703899   
11  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        67.703899   
12  Viscosity_std_817  rLine1000                 300.0         5.416312   
13  Viscosity_std_817  rLine1000                 500.0         5.416312   
14  Viscosity_std_817  rLine1000                1000.0         5.416312   
15  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.416312   
16  Viscosity_std_817  rLine1000                1000.0         5.416312   
17  Viscosity_std_817  rLine1000                 500.0         5.416312   
18  Viscosity_std_817  rLine1000                 300.0         5.416312   
19  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.416312   
20  Viscosity_std_817  rLine1000                  1000        24.223701   
21  Viscosity_std_817  rLine1000                   500        24.223701   
22  Viscosity_std_817  rLine1000                   300        24.223701   
23  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        24.223701   
24  Viscosity_std_817  rLine1000                  1000        10.682911   
25  Viscosity_std_817  rLine1000                   500        10.682911   
26  Viscosity_std_817  rLine1000                   300        10.682911   
27  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        10.682911   
28  Viscosity_std_817  rLine1000                  1000        44.695504   
29  Viscosity_std_817  rLine1000                   500        44.695504   
30  Viscosity_std_817  rLine1000                   300        44.695504   
31  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        44.695504   
32  Viscosity_std_817  rLine1000                  1000         5.706171   
33  Viscosity_std_817  rLine1000                   500         5.706171   
34  Viscosity_std_817  rLine1000                   300         5.706171   
35  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.706171   
36  Viscosity_std_817  rLine1000                  1000        13.520394   
37  Viscosity_std_817  rLine1000                   500        13.520394   
38  Viscosity_std_817  rLine1000                   300        13.520394   
39  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        13.520394   

    dispense_rate blow_out delay_aspirate delay_dispense delay_blow_out  \
0       54.163119    False             10             10              0   
1       54.163119    False             10             10              0   
2       54.163119    False             10             10              0   
3       54.163119    False             10             10              0   
4       67.703899    False             10             10              0   
5       67.703899    False             10             10              0   
6       67.703899    False             10             10              0   
7       67.703899    False             10             10              0   
8        5.416312    False             10             10              0   
9        5.416312    False             10             10              0   
10       5.416312    False             10             10              0   
11       5.416312    False             


ii.   Run BO_LiqTransfer.optimized_suggestions() method to obtain optimized aspiration and dispense rates.



In [19]:
liq.optimized_suggestions()


aspiration_rate  dispense_rate  acq_value
0          9.634237       7.542938   0.065961
1         66.962056      32.941826   0.062336
2         66.571629      27.063941   0.056918
3         66.604181      30.397830   0.044135
4         67.592016      26.033180   0.013579
5         67.504488      29.601609   0.013152
6          8.614134      11.038760   0.005319
7          7.670961      12.033662   0.004790
8          7.243785       8.907349   0.003705
9          6.699781      10.184027   0.003497
10         6.228311       7.565994   0.003397
11         5.427068      11.700832   0.003170

In [20]:
liquids_dict = {
  liquid_name :{
        "rLine1000": {
            "aspiration_rate": liq._latest_suggestion['aspiration_rate'], 
            "dispense_rate": liq._latest_suggestion['dispense_rate'], 
            "blow_out" : False, 
            "delay_aspirate" : 10, 
            "delay_dispense" : 10, 
            "delay_blow_out" : 0, 
            },
    }

}

iii. Run liquid transfer using the best suggestion for aspiration and dispense rates in OT2 notebook.


In [33]:
pipette.mover.home()

SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(207.893000,-4.081374,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (1.000x)
[207.893 -4.081 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 1.842s (0.500x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (1.000x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
Homed


True

In [ ]:
pipette.liquid.eject()

In [ ]:
pipette.mover.connect()

In [ ]:
# pipette.mover.home()
# pipette.mover.setHandedness(False)
pipette.mover.safeMoveTo(bin.wells['A1'].top)

In [36]:
#define volume
volume = 1000
liquid_level = initial_liquid_level
#Check if new tip is required
pipette.mover.setHandedness(False)
pipette.mover.setSpeed(50)

if pipette.liquid.isTipOn()== False:
    pipette.attachTip()

#Transfer start
start = time.time()

#Aspirate step
pipette.mover.safeMoveTo(source.wells['A1'].from_bottom((0,0,liquid_level-5)))
pipette.liquid.aspirate(volume, speed=liquids_dict[liquid_name][pipette_name]['aspiration_rate'])
time.sleep(liquids_dict[liquid_name][pipette_name]['delay_aspirate'])

pipette.touchTip(source.wells['A1'])

#Dispense step
pipette.mover.safeMoveTo(balance_deck.wells['A1'].from_top((0,0,-5)))

balance.tare()
balance.clearCache()
balance.toggleRecord(True)
time.sleep(5)


pipette.liquid.dispense(volume, speed=liquids_dict[liquid_name][pipette_name]['dispense_rate'])

time.sleep(liquids_dict[liquid_name][pipette_name]['delay_dispense'])

#Blowout step
if liquids_dict[liquid_name][pipette_name]['blow_out'] == True:
    pipette.liquid.blowout(home=False)
    time.sleep(liquids_dict[liquid_name][pipette_name]['delay_blow_out'])

#Transfer termination
finish = time.time()
time_m = finish - start

pipette.mover.safeMoveTo(source.wells['A1'].top)
time.sleep(5)
balance.toggleRecord(False)
if liquids_dict[liquid_name][pipette_name]['blow_out'] == True:
    pipette.liquid.home()

#Do blowout
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()
time.sleep(5)
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()
time.sleep(5)
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()


Tip capacitance: 248
Tip capacitance: 248
A1
Tip capacitance: 247
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (0.200x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
MovJ(198.894071,-3.942538,200.000000,10.000000,0.000000,0.000000)
Move time: 2.022s (0.500x)
[198.894 -3.943 200.000], [10  0  0]
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(198.894071,-3.942538,65.400000,10.000000,0.000000,0.000000)
Move time: 6.730s (0.200x)
[198.894 -3.943 65.400], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
SpeedFactor(1)
receive: SpeedFactor(1)
MovJ(198.894071,-3.942538,45.400000,10.000000,0.000000,0.000000)
Move time: 20.000s (0.010x)
[198.894 -3.943 45.400], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(198.894071,-3.942538,162.300000,10.000000,0.000000,0.000000)
Move time: 5.845s (0.200x)
[198.894 -3.943 162.300], [10  0  0]
Spee

In [15]:
pipette.liquid.dispense(200)

Dispensing 200.0 uL...
Dispense time: 2.072537900006864s


'ok'

In [ ]:
balance.toggleRecord(False)

Stop listening...


In [13]:
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()
time.sleep(5)
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()
time.sleep(5)
pipette.liquid.blowout(home=False)
time.sleep(5)
pipette.touchTip(source.wells['A1'])
pipette.liquid.home()

SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(206.843094,-146.682146,63.510000,10.000000,0.000000,0.000000)
Move time: 0.500s (0.200x)
[206.843 -146.682 63.510], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(207.104567,-129.734163,63.510000,10.000000,0.000000,0.000000)
Move time: 0.847s (0.200x)
[207.105 -129.734 63.510], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(206.581621,-163.630129,63.510000,10.000000,0.000000,0.000000)
Move time: 1.695s (0.200x)
[206.582 -163.630 63.510], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(206.843094,-146.682146,63.510000,10.000000,0.000000,0.000000)
Move time: 0.847s (0.200x)
[206.843 -146.682 63.510], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(189.895111,-146.420672,63.510000,10.000000,0.000000,0.000000)
Move time: 0.847s (0.200x)
[

'ok'

In [ ]:
fig,axs = plt.subplots()

axs.plot(balance.buffer_df['Time'],balance.buffer_df['Mass'])

axs.set_xlabel('Time')
axs.set_ylabel('Mass')

plt.show()

In [ ]:
#Record trasnfer values 

m = (balance.buffer_df.iloc[-10:,-1].mean()-balance.buffer_df.iloc[:10,-1].mean())/1000 #-1: mass column #-10: = last 10 rows #:10 = first 10 rows
error = (m-density*volume/1000)/(density/1000*volume)*100

#New dataframe
df = pd.DataFrame(columns = ['liquid', 'pipette', 'volume', 'aspiration_rate', 'dispense_rate','blow_out', 'delay_aspirate', 'delay_dispense', 'delay_blow_out', 'density', 'time', 'm', '%error', 'acq_value', 'Transfer_Observation', 'Comment'])
df = df.astype({'liquid':str,'pipette':str,'blow_out':bool,'Transfer_Observation':str,'Comment':str})
df = pd.concat([df,pd.DataFrame(liquids_dict[liquid_name][pipette_name],index=[0])],ignore_index=True)
df.iloc[-1,-6] = time_m
df.iloc[-1,2] = volume
df.iloc[-1, 0] = liquid_name
df.iloc[-1, 1] = pipette_name
df.iloc[-1,-7] = density
df.iloc[-1, -5] = m
df.iloc[-1,-4]= error
df.iloc[-1, -3] = liq._latest_acq_value

In [ ]:
#Update liquid level
#liquid_level = liquid_level - 1*volume/1000
liquid_level = liquid_level - 1.2*m/density

In [ ]:
#Observe error made
df.tail(20)

In [ ]:
#Assign category of observation of transfer such as Incomplete Dispense, Incomplete Aspiration, 
#Incomplete Aspiration and Dispense, Complete Transfer. 
#Comment if any unexpected exprimental mistakes or changes were performed that have to be taken into account.
#Incomplete Aspiration and Dispense, Complete Transfer. 
df.iloc[-1,-2]= 'Complete Transfer'
df.iloc[-1,-1]= 'Blowout before'

In [29]:
#Check if new tip is required
pipette.mover.setSpeed(50)
pipette.mover.setHandedness(False)

if pipette.liquid.isTipOn()== False:
    pipette.attachTip()

#setup for loops
#TO BE CHANGED
iterations = 3
volumes_list = [1000, 500, 300]

#NOT TO BE CHANGED
liquid_level = initial_liquid_level
counter = 1

#while loop
while counter <= iterations:
    #getting botorch suggestions + implementing it in liquids_dict
    liq.optimized_suggestions()
    liquids_dict = {
    liquid_name :{
            "rLine1000": {
                "aspiration_rate": liq._latest_suggestion['aspiration_rate'], 
                "dispense_rate": liq._latest_suggestion['dispense_rate'], 
                "blow_out" : False, 
                "delay_aspirate" : 10, 
                "delay_dispense" : 10, 
                "delay_blow_out" : 0, 
                },
        }
    }
    #for loop
    for item in volumes_list:
        volume = item
        #liquid transfer
        #transfer start
        start = time.time() 

        #aspirate step
        pipette.mover.safeMoveTo(source.wells['A1'].from_bottom((0,0,liquid_level-5))) 
        pipette.liquid.aspirate(volume, speed=liquids_dict[liquid_name][pipette_name]['aspiration_rate'])
        time.sleep(liquids_dict[liquid_name][pipette_name]['delay_aspirate'])

        pipette.touchTip(source.wells['A1']) 

        #dispense step
        pipette.mover.safeMoveTo(balance_deck.wells['A1'].from_top((0,0,-5))) 
        balance.tare() 
        balance.clearCache() 
        balance.toggleRecord(True) 
        time.sleep(5)
        pipette.liquid.dispense(volume, speed=liquids_dict[liquid_name][pipette_name]['dispense_rate'])
        time.sleep(liquids_dict[liquid_name][pipette_name]['delay_dispense'])

        #blowout step
        if liquids_dict[liquid_name][pipette_name]['blow_out'] == True: 
            pipette.liquid.blowout(home=False)
            time.sleep(liquids_dict[liquid_name][pipette_name]['delay_blow_out']) 

        #transfer termination
        finish = time.time() 
        time_m = finish - start

        pipette.mover.safeMoveTo(source.wells['A1'].top) 
        time.sleep(5)
        balance.toggleRecord(False) 
        if liquids_dict[liquid_name][pipette_name]['blow_out'] == True:
            pipette.liquid.home() 

        #do blowout
        pipette.liquid.blowout(home=False) 
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()
        time.sleep(5)
        pipette.liquid.blowout(home=False)
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()
        time.sleep(5)
        pipette.liquid.blowout(home=False)
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()

        #record transfer values 
        #calculating mass error functions
        m = (balance.buffer_df.iloc[-10:,-1].mean()-balance.buffer_df.iloc[:10,-1].mean())/1000 
        error = (m-density*volume/1000)/(density/1000*volume)*100

        #making new dataframe + filling it in
        df = pd.DataFrame(columns = ['liquid', 'pipette', 'volume', 'aspiration_rate', 'dispense_rate','blow_out', 'delay_aspirate', 'delay_dispense', 'delay_blow_out', 'density', 'time', 'm', '%error', 'acq_value'])
        df = df.astype({'liquid':str,'pipette':str,'blow_out':bool})
        df = pd.concat([df,pd.DataFrame(liquids_dict[liquid_name][pipette_name],index=[0])],ignore_index=True)
        df.iloc[-1,-4] = time_m
        df.iloc[-1,2] = volume
        df.iloc[-1, 0] = liquid_name
        df.iloc[-1, 1] = pipette_name
        df.iloc[-1,-5] = density
        df.iloc[-1, -3] = m
        df.iloc[-1,-2]= error
        df.iloc[-1, -1] = liq._latest_acq_value

        #change liquid levels
        liquid_level = liquid_level - 1.2*m/density   

        #printing checks
        print("LIQUID LEVEL: " +str(liquid_level) + "   LIQUID CHANGE: " +str(1.2*m/density) + "   ITERATION: " + str(counter) + ", " + str(volume)) 
  

        #liquid level checks
        if (1.2*m/density > 1.2) or (1.2*m/density < 0):
            break
        if (liquid_level > initial_liquid_level) or (liquid_level < 6):
            break
        
        #update main dataframe
        liq.update_data(df)  


        

    if (1.2*m/density > 1.2) or (1.2*m/density < 0):
        break
    if (liquid_level > initial_liquid_level) or (liquid_level < 6):
        break  
    counter += 1




Tip capacitance: 247
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (1.000x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
MovJ(206.843094,-146.682146,200.000000,10.000000,0.000000,0.000000)
Move time: 2.934s (0.500x)
[206.843 -146.682 200.000], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(206.843094,-146.682146,55.010000,10.000000,0.000000,0.000000)
Move time: 1.450s (1.000x)
[206.843 -146.682 55.010], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
Aspirating 1000.0 uL...
Target: 1000.0 uL at 10.978675827559151 uL/s...
Best parameters: SpeedParameters(preset=150, intervals=40, step_size=10, delay=2.110474984355027)
SpeedParameters(preset=150, intervals=40, step_size=10, delay=2.110474984355027)
Speed 1: 150 uL/s
Aspiration time: 91.10571670002537s
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(206.843094,-146.682146,63.510000,10.000000,0.000000,0.000000)
Move

KeyboardInterrupt: 

In [ ]:
df

liquid    pipette volume  aspiration_rate  dispense_rate  \
0  Viscosity_std_1275  rLine1000    500        16.347177      29.368433   

   blow_out delay_aspirate delay_dispense delay_blow_out density        time  \
0     False             10             10              0  0.8736  111.046827   

         m     %error acq_value  
0  0.38019 -12.960103  0.009564

In [ ]:
pipette.attachTip()

NameError: name 'pipette' is not defined

iv. Update latest %error obtained from the transfer using suggested aspiration and dispense rates.

In [ ]:
liq.update_data(df) 


In [31]:

liq._data 

liquid    pipette                volume  aspiration_rate  \
0   Viscosity_std_817  rLine1000                1000.0        54.163119   
1   Viscosity_std_817  rLine1000                 500.0        54.163119   
2   Viscosity_std_817  rLine1000                 300.0        54.163119   
3   Viscosity_std_817  rLine1000  mean[100, 500, 1000]        54.163119   
4   Viscosity_std_817  rLine1000                 300.0        67.703899   
5   Viscosity_std_817  rLine1000                 500.0        67.703899   
6   Viscosity_std_817  rLine1000                1000.0        67.703899   
7   Viscosity_std_817  rLine1000  mean[100, 500, 1000]        67.703899   
8   Viscosity_std_817  rLine1000                 300.0        67.703899   
9   Viscosity_std_817  rLine1000                 500.0        67.703899   
10  Viscosity_std_817  rLine1000                1000.0        67.703899   
11  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        67.703899   
12  Viscosity_std_817  rLine1000                 300.0         5.416312   
13  Viscosity_std_817  rLine1000                 500.0         5.416312   
14  Viscosity_std_817  rLine1000                1000.0         5.416312   
15  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.416312   
16  Viscosity_std_817  rLine1000                1000.0         5.416312   
17  Viscosity_std_817  rLine1000                 500.0         5.416312   
18  Viscosity_std_817  rLine1000                 300.0         5.416312   
19  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.416312   
20  Viscosity_std_817  rLine1000                  1000        24.223701   
21  Viscosity_std_817  rLine1000                   500        24.223701   
22  Viscosity_std_817  rLine1000                   300        24.223701   
23  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        24.223701   
24  Viscosity_std_817  rLine1000                  1000        10.682911   
25  Viscosity_std_817  rLine1000                   500        10.682911   
26  Viscosity_std_817  rLine1000                   300        10.682911   
27  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        10.682911   
28  Viscosity_std_817  rLine1000                  1000        44.695504   
29  Viscosity_std_817  rLine1000                   500        44.695504   
30  Viscosity_std_817  rLine1000                   300        44.695504   
31  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        44.695504   
32  Viscosity_std_817  rLine1000                  1000         5.706171   
33  Viscosity_std_817  rLine1000                   500         5.706171   
34  Viscosity_std_817  rLine1000                   300         5.706171   
35  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.706171   
36  Viscosity_std_817  rLine1000                  1000        13.520394   
37  Viscosity_std_817  rLine1000                   500        13.520394   
38  Viscosity_std_817  rLine1000                   300        13.520394   
39  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        13.520394   
40  Viscosity_std_817  rLine1000                  1000         9.634237   
41  Viscosity_std_817  rLine1000                   500         9.634237   
42  Viscosity_std_817  rLine1000                   300         9.634237   
43  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         9.634237   
44  Viscosity_std_817  rLine1000                  1000         5.663288   
45  Viscosity_std_817  rLine1000                   500         5.663288   
46  Viscosity_std_817  rLine1000                   300         5.663288   
47  Viscosity_std_817  rLine1000  mean[100, 500, 1000]         5.663288   
48  Viscosity_std_817  rLine1000                  1000        67.504488   
49  Viscosity_std_817  rLine1000                   500        67.504488   
50  Viscosity_std_817  rLine1000                   300        67.504488   
51  Viscosity_std_817  rLine1000  mean[100, 500, 1000]        67.504488   

    dispense_rate blow_out delay_aspira

v. Iterate trhough last two code cells.

In [ ]:
"C:\Users\admin\Documents\GitHub\viscosity_liquid_transfer_Pablo\Sartorious_experiments\Experimental_Data\Batch_optimization_data\BOTorch\SOBO"

In [32]:
#save after each standard-experiment iteration
import os
REPO = 'viscosity_liquid_transfer_Pablo'
folder = os.getcwd().split(REPO)[0]+REPO+r'\Sartorious_experiments\Experimental_Data\\Batch_optimization_data\BOTorch\SOBO\\' #folder that data is saved to
liq._data.to_csv(folder+liquid_name+'_SOBO_BOTorch_exp3_v1.csv', index = False)

In [30]:
pipette.ejectTipAt(bin.wells['A1'].top)
pipette.mover.home()

Tip capacitance: 247
SetArmOrientation(1,1,1,1)
receive: SetArmOrientation(1,1,1,1)
MovJ(320.000000,-240.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 1.132s (1.000x)
[320.000 -240.000 200.000], [10  0  0]
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(320.000000,-240.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (0.200x)
[320.000 -240.000 200.000], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(232.616399,194.960923,200.000000,10.000000,0.000000,0.000000)
Move time: 4.350s (1.000x)
[232.616 194.961 200.000], [10  0  0]
SpeedFactor(20)
receive: SpeedFactor(20)
MovJ(232.616399,194.960923,114.400000,10.000000,0.000000,0.000000)
Move time: 4.280s (0.200x)
[232.616 194.961 114.400], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(232.616399,194.960923,200.000000,10.000000,0.000000,0.000000)
Move time: 0.856s (1.000x)
[232.616 194.961 200.000], [10  0  0]
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 1.950s (

True

In [ ]:
        pipette.liquid.blowout(home=False) 
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()
        time.sleep(5)
        pipette.liquid.blowout(home=False)
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()
        time.sleep(5)
        pipette.liquid.blowout(home=False)
        time.sleep(5)
        pipette.touchTip(source.wells['A1'])
        pipette.liquid.home()

In [ ]:
pipette.liquid.eject()

In [ ]:
pipette.mover.connect()

In [ ]:
liq._data = liq._data.drop(35)

In [ ]:
pipette.liquid.dispense(1000)

In [ ]:
pipette.mover.connect()

In [27]:
pipette.mover.home()

SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(206.843094,-146.682146,200.000000,10.000000,0.000000,0.000000)
Move time: 1.265s (1.000x)
[206.843 -146.682 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 2.934s (0.500x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(100)
receive: SpeedFactor(100)
MovJ(300.000000,0.000000,200.000000,10.000000,0.000000,0.000000)
Move time: 0.000s (1.000x)
[300.000 0.000 200.000], [10  0  0]
SpeedFactor(50)
receive: SpeedFactor(50)
Homed


True

In [ ]:
pipette.liquid.connect()

In [ ]:
balance.connect()

In [ ]:
std = '1275'
liquid_name = 'Viscosity_std_' + std 
density = 0.8736
# Do not change
liq = BO_LiqTransfer(liquid_name)
folder = (r"C:\Users\admin\Documents\GitHub\viscosity_liquid_transfer_Pablo\Sartorious_experiments\Initialisation_Data")
liq.data_from_csv(liquid_name+'_BOTorch_exp3.csv')
liq._data